# Generated by Django 3.2 on 2022-03-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='feature_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
